
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-bears-app:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: "build the bears app"
          command: bash ./mv-bears-app.sh
      - run:
          name: "move the bears-app module into the usagov-2021 directory"
          command: |
            pwd
            ls -l
            cp -r  usagov_bears usagov-2021/web/modules/custom/
            ls -l usagov-2021/web/modules/custom/

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-bears-app


            
          