
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-bears-app:
    machine:
      image: ubuntu-2004:202107-02
    # docker:
    #   - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: Cloning the Repo and initiating the Submodule
          command: |
            echo "cloning the repo and initiating the usagov-2021 submodule"
            git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL"
            cd px-bears-drupal
            git submodule init
            git submodule update

      - run:
          name: Moving the bears app into usagov-2021 module
          command: |
            cd px-bears-drupal
            bash ./mv-bears-app.sh
            echo ".................."
            echo "moving the bears-app module into the usagov-2021 directory"
            mv  usagov_bears usagov-2021/web/modules/custom
            ls -l usagov-2021/web/modules/custom/

      - run: 
          name: Pre-docker-build configurations
          command: |
            cd px-bears-drupal/usagov-2021
            mv .docker/Dockerfile-cms .
            sed -i 's/80/8080/g' Dockerfile-cms  
            sed -i 's/80/8080/g' .docker/src-cms/etc/nginx/partials/cms.conf.tmpl
            sed -i 's/80/8080/g' .docker/src-cms/etc/nginx/partials/www.conf.tmpl

      - run: 
          name: Building, tagging, pushing the Docker Image
          command: |
            export IMAGE_TAG=$( echo $CIRCLE_WORKFLOW_ID | cut -b -8 )
            export DOCKERREPO="ghcr.io/gsa/px-bears-drupal/bears-cms"
            export CR_PAT=$( echo $CR_PAT)
            cd px-bears-drupal/usagov-2021
            echo "echoing the image tag: $IMAGE_TAG"
            ls -l
            docker build -f ./Dockerfile-cms -t "$DOCKERREPO:$IMAGE_TAG" .
            docker images
            echo "$CR_PAT" | docker login --username USERNAME --password-stdin
            docker push "$DOCKERREPO:$IMAGE_TAG"

      - run:
          name: Changing the manifest yml
          command: |
            export IMAGE_TAG=$( echo $CIRCLE_WORKFLOW_ID | cut -b -8 )
            export DOCKERREPO="ghcr.io/gsa/px-bears-drupal/bears-cms"
            export CR_PAT=$( echo $CR_PAT)
            cd px-bears-drupal/usagov-2021
            sed -i "s#^    image: .*cms-latest*#    image: $DOCKERREPO:$IMAGE_TAG#" manifest.yml  
            cat manifest.yml

      - install-cloud-foundry

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-bears-app


            
          