
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-bears-app:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run:
          name: Cloning and Making Changes to the Repo
          command: |
            echo "cloning the repo and initiating the usagov-2021 submodule"
            git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL"
            cd px-bears-drupal
            git submodule init
            git submodule update
            echo "building the bears app in the same step"
            bash ./mv-bears-app.sh
            echo ".................."
            echo "moving the bears-app module into the usagov-2021 directory"
            mv  usagov_bears usagov-2021/web/modules/custom
            ls -l usagov-2021/web/modules/custom/
      - run:
          name: "testing...."
          working_directory: ~/px-bears-drupal/
          command: |
            cd px-bears-drupal
            pwd
            ls -l
            cd usagov-2021
            ls -l
      # - run:
      #     name: "move the bears-app module into the usagov-2021 directory"
      #     command: |
      #       git pull --recurse-submodules 
      #       pwd
      #       ls -l
      #       cd usagov-2021
      #       pwd
      #       ls -l
      #       mv  usagov_bears usagov-2021/web/modules/custom
      #       ls -l usagov-2021/web/modules/custom/

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-bears-app


            
          