
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-bears-app:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run:
          name: Cloning and Making Changes to the Repo
          command: |
            bash bin/pipeline/initial-setup.sh

      # - run:
      #     name: "move the bears-app module into the usagov-2021 directory"
      #     command: |
      #       git pull --recurse-submodules 
      #       pwd
      #       ls -l
      #       cd usagov-2021
      #       pwd
      #       ls -l
      #       mv  usagov_bears usagov-2021/web/modules/custom
      #       ls -l usagov-2021/web/modules/custom/

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-bears-app


            
          