name: Stale Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'
    
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v3.0.0
      with:
        repo-token: '${{ secrets.ADD_TO_PROJECT_PAT }}'
        days-before-stale: 120
        days-before-delete: 180
        comment-updates: true
        max-issues: 20
        tag-committer: true
        stale-branch-label: stale branch
        compare-branches: 'info'
        branches-filter-regex: '^((?!dependabot))'