---
name: Benefit-finder uswds version sync

on:
    workflow_dispatch:
    schedule:
        - cron: '0 6 * * 1'

jobs:
    uswds-version-check:
        runs-on: ubuntu-latest
        environment: ${{ github.head_ref || github.ref_name }}
        steps:      
            - name: Cloning the Repo and initiating the Submodule
              run: |
                echo "cloning the repo and initiating the usagov-2021 submodule"
                git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL"
                cd px-bears-drupal
                git submodule init
                git pull --recurse-submodules
                echo "usagov-2021/*" >> .gitignore

            - name: Run the script
              run: |
                pwd
                source bin/check-uswds-version.sh
            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v5
              with:
                token: ${{ secrets.ADD_TO_PROJECT_PAT }}
                commit-message: Update USDWS version
                committer: GitHub <noreply@github.com>
                author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                signoff: false
                branch: example-patches
                delete-branch: true
                title: '[USDWS Version Sync] Update Version'
                body: |
                  Update report
                  - Updated with *today's* date
                  - Auto-generated by [create-pull-request][1]
    
                  [1]: https://github.com/peter-evans/create-pull-request
                labels: |
                  USDWS version sync
                  automated pr
                assignees: ${{ env.TECH_LEAD }}
                reviewers: ${{ env.TECH_LEAD }}
                milestone: 1
                draft: true
