---
name: Benefit-finder uswds version sync

on:
    workflow_dispatch:
    schedule:
        - cron: '0 6 * * 1'

jobs:
    uswds-version-check:
        runs-on: ubuntu-latest
        environment: ${{ github.head_ref || github.ref_name }}
        steps:    

            - name: Install github command line tool
              run: |
                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                sudo apt update
                sudo apt install gh

            - name: Cloning the Repo and initiating the Submodule
              env:
                GITHUB_TOKEN: '${{ secrets.ADD_TO_PROJECT_PAT }}'
              run: |
                echo "cloning the repo and initiating the usagov-2021 submodule"
                gh repo clone GSA/px-bears-drupal
                echo ".............................................................."
                cd px-bears-drupal
                git submodule init
                echo ".............................................................."
                git branch --show-current  
                echo ".............................................................."
                git submodule update --recursive
                echo ".............................................................."
                # echo "usagov-2021/*" >> .gitignore

            # - name: Checkout
            #   uses: actions/checkout@v3

            - name: Run the script
              run: |
                cd px-bears-drupal
                bash check-uswds-version.sh
                echo ".............................................................."
                cd usagov-2021
                git branch --show-current   
                git log | head
                cd ..
                pwd
                git submodule deinit --all


            # - name: Make changes to pull request
            #   run: date +%s > report.txt

            - name: Create Pull Request
              env:
                GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
                Tech_lead: ${{ vars.TECH_LEAD }}
              uses: peter-evans/create-pull-request@v5
              with:
                token: ${{ secrets.ADD_TO_PROJECT_PAT }}
                commit-message: Update USDWS version
                committer: GitHub <noreply@github.com>
                author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                signoff: false
                title: '[USDWS Version Sync] Update Version'
                body: |
                  Update report
                  - This PR is for ${Tech_lead}.
                  - Updated with *today's* date
                  - Auto-generated by [create-pull-request][1]
    
                  [1]: https://github.com/peter-evans/create-pull-request
                labels: |
                  USDWS version sync
                  automated pr
                assignees: ${Tech_lead}
                reviewers: ${Tech_lead}
